BattleBanana optin command fix attempt 1
BattleBanana/BattleBanana pull request #21
Opened 2022-07-18 21:08 UTC by zen0-5338

Title

2022-07-19 21:29 UTC, DeveloperAnonymous requested changes

2022-07-19 21:29 UTC, DeveloperAnonymous commented on dueutil/botcommands/util.py
> +    # player = details["author"]
On a side note, we don't want to keep commented code, it pollutes the code and is pretty much useless

2022-07-20 08:12 UTC, zen0-5338 commented on .gitignore
> +*speedup*
Changed

2022-07-20 08:34 UTC, zen0-5338 commented on dueutil/botcommands/util.py
> +    player = players.find_player(details["author"])
Changed in new commit

2022-07-20 13:56 UTC, DeveloperAnonymous approved these changes

2022-07-20 16:52 UTC, merged