Ratelimit function error fix
BattleBanana/BattleBanana pull request #22
Opened 2022-08-08 17:24 UTC by zen0-5338

2 lines of code shouldn't break the bot

2022-08-08 20:03 UTC, zen0-5338 reviewed
Mistake in commit, I **added** the donor only feature

2022-08-08 21:13 UTC, DeveloperAnonymous requested changes

2022-08-08 21:13 UTC, DeveloperAnonymous commented on dueutil/botcommands/quest.py
> +    if draw > 0:
You should just display it like the others and not bother

2022-08-08 21:13 UTC, DeveloperAnonymous commented on dueutil/botcommands/quest.py
> +    battle_embed.set_footer(text="If the money is negative, then you lost more money from losing battles than you gained from winning them.")
Could put the real turn average here 😛

2022-08-08 21:13 UTC, DeveloperAnonymous commented on dueutil/commands.py
> +            if player is None:
At this point, you could put it directly under where its defined, that way it doesn't execute any useless code

2022-08-08 21:13 UTC, DeveloperAnonymous commented on dueutil/botcommands/quest.py
> +            def attr_gain(stat):
Since the whole "calculating the stats gain" part is a huge deal and duplicated, it could and should be refactored into its own function in the `players.py` module and return the gained values

2022-08-08 21:13 UTC, DeveloperAnonymous commented on dueutil/botcommands/quest.py
> +    #    battle_embed.add_field(name="Total turns", value=(str(round(totalTurns))))
No dead code.. I'm surprised sonarcloud didn't say anything about that

2022-08-09 02:34 UTC, zen0-5338 commented on dueutil/botcommands/quest.py
> +    totalCash = 0
Ew what is this convention, camelCase best

2022-08-09 04:49 UTC, zen0-5338 commented on dueutil/botcommands/quest.py
> +            def attr_gain(stat):
Are you sure? I am doing the refactoring for !aaq. I will do for the other commands later

2022-08-09 05:03 UTC, DeveloperAnonymous commented on dueutil/botcommands/quest.py
> +            def attr_gain(stat):
Sure, but imo you should add it in the PR as well, otherwise we might forget to implement it later

2022-08-13 18:19 UTC, Theelx commented
Fwiw, camelCase is not standard Python style. You can use PascalCase for class names, and SCREAMING_SNAKE_CASE for constant global variables, but stick to snake_case for everything else.

2022-08-16 18:13 UTC, Theelx commented on dueutil/botcommands/quest.py
> +    totalCash = 0
Switch it to snake_case please.

2022-08-16 18:13 UTC, Theelx commented on dueutil/botcommands/quest.py
> +    while b < totalQuests:
Also totalQuests should be total_quests.

2022-08-17 05:44 UTC, zen0-5338 commented on dueutil/botcommands/quest.py
> +    totalCash = 0
~~No u~~
Check new commits

2022-08-17 05:45 UTC, zen0-5338 commented on dueutil/botcommands/quest.py
> +    battle_embed.set_footer(text="If the money is negative, then you lost more money from losing battles than you gained from winning them.")
Was thinking of it, will add average stats in future

2022-08-18 08:06 UTC, zen0-5338 commented
Dev merge and close PR plox

2022-08-18 23:48 UTC, DeveloperAnonymous commented on dueutil/botcommands/quest.py
> +        quest = player.quests.pop(b)
You should check into this @zen0-5338 and change this to a for loop instead

2022-08-18 23:53 UTC, DeveloperAnonymous commented on dueutil/botcommands/quest.py
> +        average_quest_battle_turns = player.misc_stats["average_quest_battle_turns"] = (player.misc_stats["average_quest_battle_turns"] + turns) / 2
Could you make a real average here? Could be something like that
```py
# On top
turns = []

# In the for-loop part
turns.append(battle_log.turn_count)

# In the calculation way down
avg_turns = avg(turns)
```

2022-08-18 23:54 UTC, DeveloperAnonymous commented on dueutil/botcommands/quest.py
> +    battle_embed.set_footer(text="If the money is negative, then you lost more money from losing battles than you gained from winning them.")
With the comment above, ezpz

2022-08-19 00:22 UTC, DeveloperAnonymous commented on dueutil/botcommands/quest.py
> +        total_turns += battle_log.turn_count
You should prob rename this to `turn_count` or really anything else because it is overriding another variable you defined above, line 217

2022-08-19 04:01 UTC, zen0-5338 commented on dueutil/botcommands/quest.py
> +        average_quest_battle_turns = player.misc_stats["average_quest_battle_turns"] = (player.misc_stats["average_quest_battle_turns"] + turns) / 2
Done

2022-08-19 20:42 UTC, DeveloperAnonymous commented on dueutil/botcommands/quest.py
> +    total_turns = 0
This variable can be removed

2022-08-19 20:43 UTC, DeveloperAnonymous commented on dueutil/botcommands/quest.py
> +    battle_embed.add_field(name="Total turns", value=(str(round(total_turns))))
This value could be changed to `sum(quest_turns_list)`

2022-08-19 20:43 UTC, DeveloperAnonymous commented on dueutil/botcommands/quest.py
> +    battle_embed.set_footer(text="If the money is negative, then you lost more money from losing battles than you gained from winning them.")
You don't use the real average here

2022-08-28 20:38 UTC, DeveloperAnonymous commented on dueutil/botcommands/quest.py
> +    total_cash = 0
You could do the same thing as the other previous and directly substract the money quest by quest.. It would also be much safer in case a quest errors during the execution.. it's very unlikely and maybe impossible, but better be safe there because we still give the stats directly for each quest won

2022-08-28 20:38 UTC, DeveloperAnonymous approved these changes
Seems good, one last minor comment

2022-08-29 16:09 UTC, merged